spring.application.name=ecommerce

# MongoDB - filled by Render environment variable
spring.data.mongodb.uri=${MONGO_URI}

# JWT - filled by Render environment variable
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method